bcp:
    resource: "@AppBundle/Controller/"
    type:     annotation
    prefix:   /

app:
    resource: '@AppBundle/Controller/'
    type: annotation
    
login_check:
    path: /login_check

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"